### ISSUE TITLE
Editor focuses when observable is changed

### ISSUE THREAD

**Issue by marius7383** [immense/knockout-tinymce#3]
Thanks for sharing your knockout binding handler for TineMCE. It's really helping a lot!

I noticed a minor issue while using it. When the editor's observable is changed programmatically and the binding's update method is called a `keyup` command is send. This causes the editor to be focused, which I think is mostly undesired. Especially in cases where the editor is not the only input control and not in the upper parts of the page, browsers like Chrome and Firefox keep changing the scroll position to the focused TineMCE editor.

I am going to send a pull request, maybe you would like to merge it.

**Comment by cmbankester** [comment]
Fixed via #4
