### ISSUE TITLE
two minor issues: null value and non-observables

### ISSUE THREAD

**Issue by marius7383** [immense/knockout-tinymce#5]
I noticed two small issues with this binding handler:
1. If a non-observable is provided the value retrieval via `valueAccessor()()` makes the binding handler crash, because a constant value cannot be called like a function. If `valueAccessor()` is wrapped within `ko.unwrap` this can be avoided.
2. If the value expression results in a null value tinyMce crashes, however not when coercing null to an empty string (""). 

I am going to provide a pull request. If you think this is helpful, feel free to merge it.

**Comment by cmbankester** [comment]
@marius7383 Thanks for this and the PR! I completely agree about point 1. I agree with point 2 only insofar as having tinymce _treat_ `null` like `""`. What I don't want is the binding handler to change an observable from `null` to `""` (or vice-versa, to change it from `""` to `null`, though that seems unlikely).

Cursorily playing around with your work at http://rawgit.com/marius7383/knockout-tinymce/null-fix/demo.html, it looks like you've handled point 2 precisely how I was hoping (I just cracked open the console, passed `null` into `view1.string_of_html` and then called `view1.string_of_html()` to ensure it was still `null`). I'll give the PR a few hours in case you need to make any changes based on this feedback, and then I'll merge it in.

Thanks again!

**Comment by marius7383** [comment]
@cmbankester Thanks for your feedback! I agree that changing the binding's value that way is definitely not how it should be done. 

In fact I find it really odd that the `setContent` method of tinyMCE is completely unaware of the possibility that the parameter `content` could be `null`. TinyMCE crashes when trying to [retrieve the property `length` of a `null` value](https://github.com/tinymce/tinymce/blob/master/js/tinymce/classes/Editor.js#L1727). Since TinyMCE isn't around since just yesterday, I presume that there is a reason why they don't accept or check a `null` parameter. However, I also find it hard to believe that this is the first time someone tries to do this. But I couldn't find some sort of hint or reason neither in the docs nor in the open issues/PRs of TinyMCE or anywhere else. 

I can think of two alternatives to the current behaviour:
1. Silently drop an update that tries to set `null` on TinyMCE. This would cause the binding and the editor to be out of sync, which I would not prefer.
2. Throw an exception in the `update` callback, if the new value is `null`, giving the user of the binding the chance to gracefully fail with a `try-catch`-block, since it doesn't seem to be possible to produce a `null` value via the UI. But, this would also cause the binding and the editor to be out of sync, which doesn't make this solution better than the first.

For now I think coercing to an empty string isn't the worst way of handling things, but not the best either. So I don't mind if you merge the PR. Maybe we can come up with a better solution in the future?

**Comment by cmbankester** [comment]
Thanks again for your help, @marius7383. I merged it in as is
