### ISSUE TITLE
Binding Issue

### ISSUE THREAD

**Issue by derekang** [immense/knockout-tinymce#9]
Hi, 

I got this error when i tried to intregrate this plugin in my web app.

knockout.js?ver=6:72 Uncaught TypeError: Unable to process binding "tinymce: function (){return string_of_html }"
Message: $(...).tinymce is not a functionupdate @ knockout-tinymce.js?ver=6:38function.a.B.i @ knockout.js?ver=6:72Pc @ knockout.js?ver=6:51Qc @ knockout.js?ver=6:51aa @ knockout.js?ver=6:50a.m.a.B @ knockout.js?ver=6:49(anonymous function) @ knockout.js?ver=6:72q @ knockout.js?ver=6:11m @ knockout.js?ver=6:71k @ knockout.js?ver=6:69g @ knockout.js?ver=6:69k @ knockout.js?ver=6:69a.Rb @ knockout.js?ver=6:75(anonymous function) @ require-campaigns.js?v=1:96j @ jquery.js:3099fireWith @ jquery.js:3211ready @ jquery.js:3417I @ jquery.js:3433
knockout-tinymce.js?ver=6:20 Uncaught TypeError: $element.tinymce is not a function

**Comment by cmbankester** [comment]
Hey @derekang, would you mind showing me the code you're using to integrate this plugin into your web app?

Also, note that you do need to include [knockout.js](http://knockoutjs.com/downloads/index.html) >= 3.4.0, [tinymce.js](https://www.tinymce.com/download/) >= 4.1.7 and [jQuery](https://code.jquery.com/) >= 2.1.1 for this plugin to work. For example, you need to do something like this:

``` html
<script src="//code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/knockout/3.4.0/knockout-min.js"></script>
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
<script src="/path/to/knockout-tinymce.js"></script>
```

**Comment by cmbankester** [comment]
Closed this due to lack of response.
